In [1]:
import pandas as pd

train = pd.read_csv('data/cat-in-the-dat/train.csv', index_col='id')

In [2]:
train.dtypes[:5]

bin_0     int64
bin_1     int64
bin_2     int64
bin_3    object
bin_4    object
dtype: object

In [3]:
summary = pd.DataFrame(train.dtypes, columns=['데이터 타입'])
summary.head()

       데이터 타입
bin_0   int64
bin_1   int64
bin_2   int64
bin_3  object
bin_4  object

In [4]:
summary = summary.reset_index()
summary.head()

   index  데이터 타입
0  bin_0   int64
1  bin_1   int64
2  bin_2   int64
3  bin_3  object
4  bin_4  object

In [5]:
summary = summary.rename(columns={'index': '피처'})
summary.head()

      피처  데이터 타입
0  bin_0   int64
1  bin_1   int64
2  bin_2   int64
3  bin_3  object
4  bin_4  object

In [6]:
summary['결측값 개수'] = train.isnull().sum().values

summary['고윳값 개수'] = train.nunique().values

summary['첫 번째 값'] = train.loc[0].values
summary['두 번째 값'] = train.loc[1].values
summary['세 번째 값'] = train.loc[2].values

summary.head()

      피처  데이터 타입  결측값 개수  고윳값 개수 첫 번째 값 두 번째 값 세 번째 값
0  bin_0   int64       0       2      0      0      0
1  bin_1   int64       0       2      0      1      0
2  bin_2   int64       0       2      0      0      0
3  bin_3  object       0       2      T      T      F
4  bin_4  object       0       2      Y      Y      Y

In [7]:
import pandas as pd

def resumetable(df):
    print(f'데이터셋 형상: {df.shape}')
    summary = pd.DataFrame(df.dtypes, columns=['데이터 타입'])
    summary = summary.reset_index()
    summary = summary.rename(columns={'index': '피처'})
    summary['결측값 개수'] = df.isnull().sum().values
    summary['고윳값 개수'] = df.nunique().values
    summary['첫 번째 값'] = df.loc[0].values
    summary['두 번째 값'] = df.loc[1].values
    summary['세 번째 값'] = df.loc[2].values

    return summary

In [8]:
resumetable(train)

데이터셋 형상: (300000, 24)

        피처  데이터 타입  결측값 개수  고윳값 개수       첫 번째 값       두 번째 값     세 번째 값
0    bin_0   int64       0       2            0            0          0
1    bin_1   int64       0       2            0            1          0
2    bin_2   int64       0       2            0            0          0
3    bin_3  object       0       2            T            T          F
4    bin_4  object       0       2            Y            Y          Y
5    nom_0  object       0       3        Green        Green       Blue
6    nom_1  object       0       6     Triangle    Trapezoid  Trapezoid
7    nom_2  object       0       6        Snake      Hamster       Lion
8    nom_3  object       0       6      Finland       Russia     Russia
9    nom_4  object       0       4      Bassoon        Piano   Theremin
10   nom_5  object       0     222    50f116bcf    b3b4d25d0  3263bdce5
11   nom_6  object       0     522    3ac1b8814    fbcb50fc1  0922e3cb8
12   nom_7  object       0    1220    68f6ad3e9    3b6dd5612  a6a36f527
13   nom_8  object       0    2215    c389000ab    4cd920251  de9c9f684
14   nom_9  object       0   11981    2f4cb3d51    f83c56c21  ae6800dd0
15   ord_0   int64       0       3            2            1          1
16   ord_1  object       0       5  Grandmaster  Grandmaster     Expert
17   ord_2  object       0       6         Cold          Hot   Lava Hot
18   ord_3  object       0      15            h            a          h
19   ord_4  object       0      26            D            A          R
20   ord_5  object       0     192           kr           bF         Jc
21     day   int64       0       7            2            7          7
22   month   int64       0      12            2            8          2
23  target   int64       0       2            0            0          0